apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelapi-deployment
  labels:
    app: modelapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modelapi
  template:
    metadata:
      labels:
        app: modelapi
    spec:
      containers:
      - name: modelapi
        image: modelapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: modelapi-service
spec:
  selector:
    app: modelapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080